; custom.ini
memory_limit=1G
date.timezone = "Asia/Shanghai"
curl.cainfo=/etc/pki/tls/certs/ca-bundle.crt

[Phar]
; https://php.net/phar.readonly
phar.readonly = Off

; https://php.net/phar.require-hash
;phar.require_hash = On

;phar.cache_list =